mn_Home-task-06
MaryAnat/autotesting-HomeTasks-course-tms pull request #3
Opened 2020-11-22 15:43 UTC by MaryAnat

2020-11-26 07:35 UTC, MaryAnat commented
@vshvets 
Я, к сожалению, не очень знаю как правильно добавлять ревьюера в пулл реквест.
Вас я добавить-удалить раз 10, наверное, уже сделала. Но похоже этот пулл реквест вы все равно не видите.
Возможно, адресный комментарий поможет найти.
Я бы очень хотела получить хоть какой-нибудь фид-бек по своему домашнему заданию

2020-11-26 13:45 UTC, vshvets requested changes
1. Используй код форматинг идеи. лучше делать это постоянно. В крайнем случае перед пушем https://www.jetbrains.com/help/idea/reformat-and-rearrange-code.html#reformat_file
2. Бефор метод используешь ок. Но, где сет пути к хром драйверу. Где сам хромдрайвер. Тесты нельзя запустить без этого
3. Нэйминг - смотри комменты
В целом неплохо

2020-11-26 13:45 UTC, vshvets commented on src/test/java/TestAddRemoveEl.java
> +        driver=new ChromeDriver();
где путь хромдрайверу

2020-11-26 13:45 UTC, vshvets commented on src/test/java/TestAddRemoveEl.java
> +        driver=null;
лишняя строчка. часто в дз встречается, так и не понл зачем она

2020-11-26 13:45 UTC, vshvets commented on src/test/java/TestAddRemoveEl.java
> +        int num_el=driver.findElements(By.xpath("//*[@onclick='deleteElement()']")).size();
нэйминг некорректный. Не надо сокращать в таких маленьких словах и _ нельзя добовлять. Java name convention

2020-11-26 13:45 UTC, vshvets commented on src/test/java/TestCheckBoxes.java
> +        Assert.assertEquals(checkBoxFirst.isSelected(),false);
Смотри, что тебе идея подсказывает. тут проще можно писать
Assert.assertFalse(checkBoxFirst.isSelected())

2020-11-26 13:45 UTC, vshvets commented on src/test/java/TestDropdown.java
> +    public void testDropdownEls(){
Опять нэйминг...

2020-11-26 13:45 UTC, vshvets commented on src/test/java/TestHover.java
> +//        Вопрос к преподавателю - есть ли возможноть в xpath и в assert использовать переменные?
Конечно. Тот же икспас это же стринга, создаешь стрингу - туда икспас. Но лучше вместо этого использовать методы. Т.е. создаешь методы и в тестах их юзаешь. Второе для циклов в тестах используется дата провайдер или параметрайзд тест. Будем проходить чутка позже, интересно сейчас почитай
https://testng.org/doc/documentation-main.html#parameters-dataproviders

2020-11-26 15:22 UTC, MaryAnat commented on src/test/java/TestAddRemoveEl.java
> +        driver=new ChromeDriver();
Хромдрайвер лежит в директории, которая включена в Path, поэтому в тесте прописывать не требуется.
Такое размещение хромдрайвера имеет ряд преимуществ в долгосрочной перспективе.

2020-11-26 15:29 UTC, MaryAnat commented on src/test/java/TestAddRemoveEl.java
> +        driver=null;
Можно подробнее, пжта, что здесь считается "лишней" строчкой?
На 26 стр находится закрывающая кавычка }
Потом идет пустая срока - разделитель перед следующим логическим блоком кода - стр 27
С 28 стр - @Test
Если удалить стр 27 - код будет сливаться в одно сплошное полотно, что сделает его трудно читаемым.
Или возможно, я неправильно понимаю ваше замечание.
Поэтому прошу пояснить подробнее, если несложно.

2020-11-26 15:48 UTC, vshvets commented on src/test/java/TestAddRemoveEl.java
> +        driver=new ChromeDriver();
Хммм. Не понял в какой перспективе, но тесты могут запускаться только на твоем компьютере. Другие ими не могут пользоваться.

2020-11-26 15:48 UTC, vshvets commented on src/test/java/TestAddRemoveEl.java
> +        driver=null;
про драйвер нал.
driver=null; Какой смысл? я не понял

2020-11-27 08:45 UTC, MaryAnat commented on src/test/java/TestAddRemoveEl.java
> +        driver=null;
Гугл подсказал, что это хорошая практика обнулять переменную перед каждым запуском теста. Т.е. когда не один тест, а их несколько, важно это делать после каждого теста. Таким образом мы получаем в свое распоряжение чистый инстанс браузера и страхуемся от ситуации, когда  просто забивается оперативная память и нарушается работа операционной системы

2020-11-27 09:28 UTC, MaryAnat commented on src/test/java/TestAddRemoveEl.java
> +        driver=new ChromeDriver();
Ну не знаю как на этот комментарий ответить корректно.
У Алексей Баранцева есть очень хорошее видео на мин 10, где он подробно описывается преимущества и недостатки размещения вспомогательного исполняемого файла (т.е. драйвера) в разных директориях.

Основные минусы размещения в папке проекта:
- механизмы поиска ВИФ селениумом на разных языках программирования на разных клиентских библиотеках реализован по разному. И селениум просто банально не найдет этот файл в папку проекта. Это очень подробно объясняется в видео.
- ВИФ для разных ОС называются одинаково,  и если положить в текущую директория, то невозможно будет запускать эти тесты и на линукс, и на макОС
- если у меня несколько проектов, то при обновлении драйвера потребуется его обновить во всех проектах.

Поэтому тут я согласна с Баранцевым, чем с вашим подходом - "другие" должны корректно настроить размещение вспомогательного исполняемого файла локально.

2020-11-30 11:58 UTC, vshvets commented on src/test/java/TestAddRemoveEl.java
> +        driver=new ChromeDriver();
А как я узнаю от этом? как я узнаю, что надо настраивать? я может не смотрел то видео. Если хчоешь устанавливать свои правила на проекте - это ок. Только надо их донести и согласовать со всеми членами проекта, коим я являюсь. МОжно в ридми например это написать, написать мне, чтобя я прочитал это итд
То, что ты согласна с баранцевым, не поможет твоему реквесту замержится(

2020-11-30 11:58 UTC, vshvets commented on src/test/java/TestAddRemoveEl.java
> +        driver=null;
У джавы есть гарбэйдж коллектор, он все сделает сам

2020-11-30 16:54 UTC, merged